"""Exercises for 07_optimisation/04_curve_fitting_and_calibration.ipynb"""
import numpy as np
import pandas as pd

COMMON_SETUP = """
import numpy as np
import pandas as pd
from scipy import optimize
"""

_TOY = """
x = np.array([5.0, 10.0, 15.0, 20.0, 25.0, 30.0])      # temperature
y = np.array([25.0, 15.0, 5.0, 5.0, 5.0, 5.0])          # demand, generated by a=5, b=2, Th=15

def model(x_, a, b, Th):
    return a + b * np.maximum(Th - x_, 0)
"""

QUESTIONS = [
    dict(
        prompt="Write the heating-degree model `y = a + b * max(Th - x, 0)` as a function `model(x_, a, b, Th)` and evaluate it at the six temperatures in `x` with a=5, b=2, Th=15. (Check: at x=5 the value is 5 + 2·10 = 25.)",
        setup="x = np.array([5.0, 10.0, 15.0, 20.0, 25.0, 30.0])",
        solution="def model(x_, a, b, Th):\n    return a + b * np.maximum(Th - x_, 0)\n\nanswer = model(x, 5, 2, 15)",
        hint="np.maximum(Th - x_, 0) is the vectorised max(., 0). Return a + b * that.",
    ),
    dict(
        prompt="Compute the residual vector `model(x) - y` at the starting point p0 = (a=0, b=1, Th=10).",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]",
        solution="answer = model(x, *p0) - y",
        hint="Unpack p0 into the model with *p0, then subtract y.",
    ),
    dict(
        prompt="Compute the sum of squared errors (SSE) at the same starting point p0.",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]",
        solution="answer = ((model(x, *p0) - y) ** 2).sum()",
        hint="Square the residual vector and sum it.",
    ),
    dict(
        prompt="Fit the model to `x`, `y` with `optimize.curve_fit` starting from p0. Assign the fitted parameters `popt` (they should recover a=5, b=2, Th=15).",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]",
        solution="popt, pcov = optimize.curve_fit(model, x, y, p0=p0)\nanswer = popt",
        hint="optimize.curve_fit(model, x, y, p0=p0) returns (popt, pcov).",
        tol=1e-3,
    ),
    dict(
        prompt="Now fit the noisy data `y_noisy` (same p0) and assign the parameter standard errors, i.e. the square roots of the diagonal of `pcov`.",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]\nnoise = np.array([0.3, -0.2, 0.1, 0.4, -0.3, 0.2])\ny_noisy = y + noise",
        solution="popt, pcov = optimize.curve_fit(model, x, y_noisy, p0=p0)\nanswer = np.sqrt(np.diag(pcov))",
        hint="np.sqrt(np.diag(pcov)).",
        tol=1e-3,
    ),
    dict(
        prompt="Redo the noisy fit with `optimize.least_squares` (write a residual function of theta) with bounds a ∈ (−∞, ∞), b ∈ [0, 10], Th ∈ [16, 30], starting from [0, 1, 20]. Assign the fitted parameters to `theta` and `res.cost` to `cost`. Which parameter sits on a bound?",
        setup=_TOY + "noise = np.array([0.3, -0.2, 0.1, 0.4, -0.3, 0.2])\ny_noisy = y + noise",
        solution="def residuals(theta_):\n    a, b, Th = theta_\n    return model(x, a, b, Th) - y_noisy\n\nres = optimize.least_squares(residuals, x0=[0.0, 1.0, 20.0], bounds=([-np.inf, 0.0, 16.0], [np.inf, 10.0, 30.0]))\ntheta = res.x\ncost = res.cost",
        hint="least_squares(fun, x0, bounds=(lower_list, upper_list)). res.cost is 0.5·SSE.",
        answer_var=["theta", "cost"],
        tol=1e-3,
        note="Th lands on its lower bound 16 because the true value 15 is outside the allowed range.",
    ),
    dict(
        prompt="`y_spike` is the clean data with one corrupted point. Fit it twice with `least_squares` from p0: once with the default loss and once with `loss='soft_l1', f_scale=1.0`. Assign the robust fit's parameters to `theta_robust` and the plain fit's to `theta_plain`.",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]\ny_spike = y.copy(); y_spike[3] = 30.0",
        solution="def residuals(theta_):\n    a, b, Th = theta_\n    return model(x, a, b, Th) - y_spike\n\ntheta_plain = optimize.least_squares(residuals, x0=p0).x\ntheta_robust = optimize.least_squares(residuals, x0=p0, loss='soft_l1', f_scale=1.0).x",
        hint="Same residual function; only the loss= and f_scale= arguments change.",
        answer_var=["theta_plain", "theta_robust"],
        tol=1e-2,
        note="The robust fit stays near (5, 2, 15); the plain fit is dragged by the spike.",
    ),
    dict(
        prompt="Standard errors by hand. From a `least_squares` fit `res` on `y_noisy` (start p0, no bounds): sigma² = SSE / (n − p), cov = sigma² · (JᵀJ)⁻¹ with J = `res.jac`, se = sqrt(diag(cov)). Assign `se`.",
        setup=_TOY + "p0 = [0.0, 1.0, 10.0]\nnoise = np.array([0.3, -0.2, 0.1, 0.4, -0.3, 0.2])\ny_noisy = y + noise\n\ndef residuals(theta_):\n    a, b, Th = theta_\n    return model(x, a, b, Th) - y_noisy\n\nres = optimize.least_squares(residuals, x0=p0)",
        solution="J = res.jac\nsse = (res.fun ** 2).sum()\nn, p = len(y_noisy), len(res.x)\nsigma2 = sse / (n - p)\ncov = sigma2 * np.linalg.inv(J.T @ J)\nse = np.sqrt(np.diag(cov))",
        hint="res.fun is the residual vector, res.jac the Jacobian. n=6 points, p=3 parameters.",
        answer_var="se",
        tol=1e-3,
    ),
    dict(
        prompt="The supply curve is `price(x) = 20 + 3·x + 0.01·x²` (x = residual load in GW). Use `optimize.brentq` on the bracket [0, 100] to find the residual load at which the price reaches 200. Assign the root.",
        setup="def price_of(x_):\n    return 20 + 3 * x_ + 0.01 * x_ ** 2",
        solution="def f(x_):\n    return price_of(x_) - 200\n\nanswer = optimize.brentq(f, 0.0, 100.0)",
        hint="brentq needs a function that is zero at the answer: price_of(x) - 200. Check the bracket ends have opposite signs.",
        tol=1e-4,
    ),
    dict(
        prompt="`ys = 1 + 2·exp(0.0005·xs)` with xs in the thousands. Fitting `exp_model` directly from p0=[1,1,1] silently fails. Fit on the scaled input `zs = xs / 1000` instead and assign `c` converted back to the original units (should be 0.0005).",
        setup="xs = np.array([1000.0, 2000.0, 3000.0, 4000.0, 5000.0])\nys = 1 + 2 * np.exp(0.0005 * xs)\n\ndef exp_model(x_, a, b, c):\n    return a + b * np.exp(c * x_)",
        solution="zs = xs / 1000\npopt_z, _ = optimize.curve_fit(exp_model, zs, ys, p0=[1, 1, 1])\nanswer = popt_z[2] / 1000",
        hint="A coefficient c on z = x/1000 equals c/1000 on x.",
        tol=1e-6,
    ),
    dict(
        prompt="Maximum likelihood for a normal distribution: minimise the negative log-likelihood of `data` over (mu, log_sigma) with `optimize.minimize` (method 'L-BFGS-B', x0=[0, 0]). Assign the fitted `mu` and `sigma` (= exp(log_sigma)). They should equal the sample mean and the ddof=0 standard deviation.",
        setup="data = np.array([2.0, 4.0, 4.0, 5.0, 7.0, 8.0])",
        solution="def nll(theta_):\n    mu_, log_sigma = theta_\n    sigma_ = np.exp(log_sigma)\n    return len(data) * np.log(sigma_) + ((data - mu_) ** 2).sum() / (2 * sigma_ ** 2)\n\nr = optimize.minimize(nll, x0=[0.0, 0.0], method='L-BFGS-B')\nmu = r.x[0]\nsigma = np.exp(r.x[1])",
        hint="nll(mu, log_sigma) = n·log(sigma) + Σ(data − mu)² / (2·sigma²). Optimise log_sigma so sigma stays positive.",
        answer_var=["mu", "sigma"],
        tol=1e-3,
    ),
    dict(
        prompt="Real data. `daily` has the 2023 daily mean temperature `T` and daily mean consumption `C`. Fit `C = a + b·max(Th − T, 0)` with `curve_fit` from p0=[25000, 300, 15] and assign the fitted parameters `popt`.",
        setup='df = pd.read_csv("../data/hourly_power_clean.csv", parse_dates=["time"])\nd23 = df[df["time"].dt.year == 2023].set_index("time")\ndaily = d23.resample("D").mean()\nT = daily["temp_c"].values\nC = daily["consumption_mwh"].values',
        solution="def hdd(T_, a, b, Th):\n    return a + b * np.maximum(Th - T_, 0)\n\npopt, pcov = optimize.curve_fit(hdd, T, C, p0=[25000, 300, 15])",
        hint="Same model shape as task 1, different data. curve_fit(hdd, T, C, p0=[25000, 300, 15]).",
        answer_var="popt",
        check_fn=lambda got, exp: (np.allclose(np.asarray(got, dtype=float), exp, rtol=1e-2),
                                   "" if np.allclose(np.asarray(got, dtype=float), exp, rtol=1e-2) else f"expected about {np.round(exp, 1)}"),
    ),
]
